feat: implement new design for built-in style
indykite/jarvis-sdk-web pull request #73
Opened 2022-05-30 12:33 UTC by hanny21

# Description

# Checklist

- [ ] `make test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message follows [commit guidelines](./doc/guides/commit-message.md#commit-message-guidelines)

## CHANGELOG

2022-06-01 13:55 UTC, dusan-kovacik-profiq commented on lib/services/core/ui/components/buttons.js
> +  aEl.style.cssText = `color: rgb(250, 250, 250); text-decoration: none;`;
I thought the linter doesn't allow us to use backticks when there's no text substitution.

2022-06-01 14:36 UTC, lorigoldman commented on lib/services/core/__integration_tests__/renderLogin.test.js
>      describe("when the 'Create an account' link is clicked", () => {
Does case matter? If it does, pls. use "When the ..."

2022-06-01 15:40 UTC, hanny21 commented on README.md
>          alreadyHaveAnAccountButton: "Custom Already have an account",
will fix it, thanks

2022-06-01 17:23 UTC, lorigoldman approved these changes

2022-06-01 17:23 UTC, lorigoldman commented on lib/services/core/exports/IKUICore/renderLogin.js
>   * @param {string} [props.redirectUri] In case you use OIDC providers you need to specify the callback redirect Uri
providers, ...URI.

2022-06-01 17:23 UTC, lorigoldman commented on lib/services/core/exports/IKUICore/renderLogin.js
>   * @param {string} [props.registrationPath="/registration"] Url where user will be redirect after clicking on register button.
URL?

2022-06-01 17:23 UTC, lorigoldman commented on lib/services/core/exports/IKUICore/renderRegister.js
>   * @param {string} [props.loginPath="/login"] Url where user will be redirect after clicking on login button.
redirected

2022-06-01 17:23 UTC, lorigoldman commented on lib/services/core/locale/src/en.json
>    "uisdk.general.error": "Oops something went wrong. Please try again.",
Oops,

2022-06-01 17:23 UTC, lorigoldman commented on lib/services/core/locale/src/en.json
>    "authapi.err.no_recovery_methods": "you have not set up a recovery methods for your account. contact system administrator",
a recovery method for your account. Contact your system administrator.

2022-06-01 20:50 UTC, maprokes requested changes
@hanny21 could you update the commit message to follow the conventional commit for breaking changes?

> BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope, introduces a breaking API change (correlating with [MAJOR](http://semver.org/#summary) in Semantic Versioning). A BREAKING CHANGE can be part of commits of any type.

https://www.conventionalcommits.org/en/v1.0.0/

2022-06-02 06:32 UTC, dusan-kovacik-profiq approved these changes
I think after you fix the comments here it's good to go ;)

2022-06-02 08:57 UTC, merged